apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: gcr.io/project897927/consumer
        env:
        - name: GOOGLE_CLOUD_PROJECT
          value: "project897927"
        - name: DB_HOST
          value: "34.72.123.42"
        - name: DB_USER
          value: "myuser"
        - name: DB_PASSWORD
          value: "paukatta"
        - name: DB_NAME
          value: "myappdb"
