apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
      - name: producer
        image: gcr.io/project897927/producer
        env:
        - name: GOOGLE_CLOUD_PROJECT
          value: "project897927"
